Update broken-link-check.yml

diff --git a/.github/workflows/broken-link-check.yml b/.github/workflows/broken-link-check.yml
--- a/.github/workflows/broken-link-check.yml
+++ b/.github/workflows/broken-link-check.yml
@@ -9,7 +9,6 @@ jobs:
   check:
     name: "Check for broken links"
     runs-on: ubuntu-latest
-    continue-on-error: true
     steps:
       - name: "Checkout code"
         uses: actions/checkout@v2
@@ -20,10 +19,14 @@ jobs:
           fail: true
           format: json
           args: --no-progress --accept '200..=299, 401, 405' .
+        continue-on-error: true
       - name: "Send Slack alert if failing"
-        if: env.lychee_exit_code != 0 # && github.ref == 'refs/heads/main'
+        if: env.lychee_exit_code != 0
         uses: slackapi/slack-github-action@v1.26.0
         env:
           SLACK_WEBHOOK_URL: "https://hooks.slack.com/triggers/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" # TODO: set as secret
         with:
           payload: ${{ steps.lychee.outputs }}
+        run: | 
+          echo "Broken links found: ${{ steps.lychee.outputs.errors}}"
+          exit 1
